# permissions for end users to edit challengetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: challenge-operator
    app.kubernetes.io/managed-by: kustomize
  name: challengetemplate-editor-role
rules:
- apiGroups:
  - apps.hexactf.io
  resources:
  - challengetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hexactf.io
  resources:
  - challengetemplates/status
  verbs:
  - get
