---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.hexactf.io
  resources:
  - challenges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hexactf.io
  resources:
  - challenges/finalizers
  verbs:
  - update
- apiGroups:
  - apps.hexactf.io
  resources:
  - challenges/status
  verbs:
  - get
  - patch
  - update
