apiVersion: apps.hexactf.io/v1alpha1
kind: Challenge
metadata:
  name: web-instance-2
  namespace: default
  labels:
    apps.hexactf.io/challengeId: "2"
    apps.hexactf.io/user: "helloworld"
spec:
  namespace: default
  definition: web-basic